on:
  push:
    branches:
    - Develop
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - run: dotnet build --configuration Release